spring:
  h2:
    console.enabled: true
  datasource:
    url: jdbc:h2:mem:testdb
#    jdbc:mysql://localhost:3306/askanything?serverTimezone=UTC&useLegacyDatetimeCode=false
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: create-drop
#  security:
#    user:
#      name: user
#      password: user
  sql:
    init:
      enabled: true