spring:
  datasource:
    url: jdbc:h2:mem:testdb
#    jdbc:mysql://localhost:3306/askanything?serverTimezone=UTC&useLegacyDatetimeCode=false
    username: sa
    password:
  jpa:
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update
  security:
    user:
      name: user
      password: user
  sql:
    init:
      enabled: true